baseURL = "https://verify.govdigital.de/"
defaultContentLanguage = "de"
theme = "ubirch_verifier"

[languages]
[languages.de]
languageName = "Deutsch"
contentDir = "content/de"
weight = 1
[languages.de.params]
title = "Verifizierung"

[languages.en]
languageName = "English"
contentDir = "content/en"
weight = 2
[languages.en.params]
title = "Verification"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
stage = "dev"
disclaimer = "demo"

[module]
  [[module.mounts]]
    source = "node_modules"
    target = "static/js/node_modules"
  [[module.mounts]]
    source = 'static/uploads'
    target = 'static/uploads'
  [[module.mounts]]
    source = 'static/font'
    target = 'static/font'
